# Generated by Django 6.0.2 on 2026-02-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medicalhistory',
            new_name='medical_history',
        ),
    ]
