# Generated by Django 6.0.2 on 2026-02-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_myappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointment',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
